In [2]:
import cv2
from PIL import Image
import numpy as np
import pytesseract

# OCR for simple images

![](images/sample1.jpeg)

In [7]:
filepath1 = 'images/sample1.jpeg'
sample1 = np.array(Image.open(filepath1))
result1 = pytesseract.image_to_string(sample1)

In [8]:
print(result1)

Tesseract sample



# OCR for images with some noise

![](images/sample2.png)

In [16]:
# Image processing

filepath2 = 'images/sample2.png'
img2 = np.array(Image.open(filepath2))
processed_img2 = np.zeros((img2.shape[0], img2.shape[1]))
img2 = cv2.normalize(img2, processed_img2, 0, 255, cv2.NORM_MINMAX)
img2 = cv2.threshold(img2, 100, 255, cv2.THRESH_BINARY)[1]
final_img2 = cv2.GaussianBlur(img2, (1, 1), 0)
print(final_img2)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [17]:
data = Image.fromarray(final_img2)
data.save('images/sample_final2.png')

![](images/sample_final2.png)

In [20]:
result2 = pytesseract.image_to_string('images/sample_final2.png')
print(result2)

Tesseract sample



In [21]:
filepath3 = 'images/bill_sample.png'
sample3 = np.array(Image.open(filepath3))
result3 = pytesseract.image_to_string(sample3)

In [23]:
print(result3)

 

John Smith INVOICE

123 10th Ave
Fake City, SK, T2ZABC
Fake Country

To Invoice# INV-0025

isa re Suite 001 Invoice Date Nov 04, 2018
st St. Suite

Fake Country Due Date Nov 10, 2018

12345 AZ

Software Development $100.00 $16700.00

Total (USD) $17120.00

 

Payment information:
Account Holder: John Smith
Account Number: 1234567
Transit number: 0909
Branch number: 9898

