In [2]:
import cv2
from PIL import Image
import numpy as np
import pytesseract

# OCR for simple images

![](images/sample1.jpeg)

In [7]:
filepath1 = 'images/sample1.jpeg'
sample1 = np.array(Image.open(filepath1))
result1 = pytesseract.image_to_string(sample1)

In [8]:
print(result1)

Tesseract sample



# OCR for images with some noise

![](images/sample2.png)

In [14]:
# Image processing

filepath2 = 'images/sample2.png'
img2 = np.array(Image.open(filepath2))
processed_img2 = np.zeros((img2.shape[0], img2.shape[1]))
img2 = cv2.normalize(img2, processed_img2, 0, 255, cv2.NORM_MINMAX)
img2 = cv2.threshold(img2, 100, 255, cv2.THRESH_BINARY)[1]
final_img2 = cv2.GaussianBlur(img2, (1, 1), 0)
print(final_img2)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [15]:
data = Image.fromarray(final_img2)
data.save('images/sample_final2.png')

OSError: cannot write mode F as PNG

In [ ]:
img = Image.open('images/')